### ISSUE TITLE
Sample subtype import

### ISSUE THREAD

**Issue by vreuter** [databio/dnameth_pipelines#18]
...is not being found, or at least a message is being generated to that effect:
```
Using base Sample because of failure in attempt to import pipeline module '/home/vpr9v/code/dnameth_pipelines/src/rrbs.py': ImportError('No module named helpers',)
```
If this is indeed a failed import, is this due to the pipelines not being installed as a package perhaps?

**Comment by vreuter** [comment]
How consequential would this even be for the bisulfite pipelines? What if any subtype-specific attributes on `Sample` are used in the pipelines?

**Comment by vreuter** [comment]
No `Sample` subtypes are defined in these pipelines, so this is a nonissue

**Comment by nsheff** [comment]
you are right. still, the error message confused you -- so is there something we should change on that side?

**Comment by nsheff** [comment]
maybe downgrade this to DEBUG?
