### ISSUE TITLE
Make sure spike-in data strand specific flag matches main data

### ISSUE THREAD

**Issue by vreuter** [databio/dnameth_pipelines#29]
Downstream analysis now has a toggle for strand specificity. @nsheff with the way the spike-in works, does it make sense to have the strand-specific flag for the spike-in:
- [ ] always on
- [ ] always off
- [x] determined (like the non-spike-in) by the pipeline parameterization
?

**Comment by nsheff** [comment]
It should use the same setting as the main alignment, since it runs through the same protocol.

**Comment by vreuter** [comment]
OK thanks
