### ISSUE TITLE
epilog error

### ISSUE THREAD

**Issue by nsheff** [databio/dnameth_pipelines#36]
```
### Epilog methylation calling (spike-in):  (02-18 21:20:02) elapsed: 0.0 _TIME_

Traceback (most recent call last):
  File "/home/ns5bc/code/dnameth_pipelines/src/rrbs.py", line 681, in <module>
    main(sys.argv[1:])
  File "/home/ns5bc/code/dnameth_pipelines/src/rrbs.py", line 568, in main
    spikein_epiconf = copy.deepcopy(param.epilog)
  File "/apps/software/standard/core/anaconda/5.2.0-py2.7/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
TypeError: 'str' object is not callable
Pipeline status: running

```

**Comment by nsheff** [comment]
Maybe related to attmap stuff?

https://mail.python.org/pipermail/tutor/2003-May/022133.html

"y overriding __getattr__, the lookup for the object's print method returns a string, which isn't callable."

**Comment by vreuter** [comment]
It's this thing again I bet: https://github.com/databio/pypiper/issues/117
`pypiper` needs to use `attmap`

**Comment by vreuter** [comment]
https://github.com/databio/pypiper/issues/122

**Comment by vreuter** [comment]
@nsheff have you retried this with updated `pypiper`?

**Comment by nsheff** [comment]
yes, we passed this in my first test, and I'm trying a complete test now...

**Comment by vreuter** [comment]
Good deal!

**Comment by nsheff** [comment]
yes it ran through all the way.
